---
- name: restart nfs service
  service:
    name: nfs-kernel-server
    state: restarted
  when: 
    - ansible_os_family == "Debian"
    - ansible_distribution_major_version < "9"

- name: restart nfs service
  service:
    name: nfs-server
    state: restarted
  when: (ansible_os_family == "Debian" and ansible_distribution_major_version >= "9") or (ansible_os_family == "RedHat" >= "7")

- name: restart nfs service
  service:
    name: nfs
    state: restarted
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version < "7"
...